### ISSUE TITLE
Nenhuma sessão é lida quando o ano inicial e final são iguais

### ISSUE THREAD

**Issue by JPTIZ** [caravelahc/paratex#25]
**Descrição**

Quando o ano inicial e final são iguais, mesmo que as datas sejam diferentes e que o final venha depois do inicial, nenhuma sessão é carregada/lida.

**Reprodução**

Executando:

```python
    interval_begin = date(2014, 4, 22)
    interval_end = date(2014, 5, 15)

    sessions = fetch_sessions_from_interval(interval_begin, interval_end)
```

Nenhuma sessão é lida. Alterando o ano de `interval_end` para 2015 carrega todas as sessões no intervalo corretamente.

**O que deveria acontecer**

Deveriam ser carregadas as sessões em um intervalo no mesmo ano.

**Comment by gabrieltron** [comment]
Vou dar uma olhada nisso :)
